// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

interface IElasticSignWallet {
    /**
     * An event emitted after this contract called another contract
     * @param contractAddr - the called contract address
     * @param signData - the params of the call
     * @param returnData - data returned from the call
     */
    event Call(address indexed contractAddr, bytes signData, bytes returnData);

    /**
     * An event emitted after user set/reset this smartcontract wallet's password
     * @param pwdhash - the password hash
     */
    event SetPassword(uint indexed pwdhash);

    /**
     * Set/reset password for this smartcontract wallet
     * @param proof1 - proof generated by the old password
     * @param expiration1 - old password signing expiry seconds
     * @param allhash1 - allhash generated by the old password
     * @param proof2 - proof generated by the new password
     * @param pwdhash2 - hash of the new password generated by ZK
     * @param expiration2 - new password signing expiry seconds
     * @param allhash2 - allhash generated by the new password
     */
    function resetPassword(
        uint[8] memory proof1,
        uint expiration1,
        uint allhash1,
        uint[8] memory proof2,
        uint pwdhash2,
        uint expiration2,
        uint allhash2
    ) external;

    /**
     * Let this contract call another contract
     * @param proof - proof generated by the password
     * @param contractAddr - the called contract address
     * @param signData - the params of the call
     * @param expiration - the password signing expiry seconds
     * @param allhash - allhash generated by the password
     */
    function call(
        uint[8] memory proof,
        address contractAddr,
        bytes calldata signData,
        uint expiration,
        uint allhash
    ) external;

    /**
     * Let this contract call multiple contracts in one tx
     * @param proof - proof generated by the password
     * @param contractAddrArr - the list of the called contract address
     * @param signDataArr - the list of each call params
     * @param expiration - the password signing expiry seconds
     * @param allhash - allhash generated by the password
     */
    function batchCall(
        uint[8] memory proof,
        address[] calldata contractAddrArr,
        bytes[] calldata signDataArr,
        uint expiration,
        uint allhash
    ) external;
}
